# Generated by Django 2.0.7 on 2018-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_name',
            field=models.CharField(default='ghansoli', max_length=20),
            preserve_default=False,
        ),
    ]
